select  * from TP3_NEWSFEED
select  * from TP3_NEWSFEED_FILE

DROP TABLE TP3_NEWSFEED
CASCADE CONSTRAINT

CREATE TABLE TP3_NEWSFEED(
N_SEQ	NUMBER PRIMARY KEY,	
G_SEQ	NUMBER,
N_FROM_NUM	NUMBER(1),	
M_ID	VARCHAR2(20)	NOT NULL,
N_CONTENT	VARCHAR2(4000)	NOT NULL,
N_TAG_FRIEND	VARCHAR2(1000),	
N_TAG_WHERE	VARCHAR2(20),	
N_TAG_FEEL	NUMBER(1),	
N_SHOW	NUMBER(1)	NOT NULL,
N_WDATE	DATE	NOT NULL,
N_REPORT	NUMBER(1),	
N_REF	NUMBER,
N_STEP	NUMBER,	
N_DEPTH	NUMBER,
N_DEL	NUMBER(1),	
N_SHARE	NUMBER(1),	
N_EVENT_SEQ	NUMBER(1),	
N_VOTE_SEQ	NUMBER(1)	
)

SELECT *
     FROM USER_SEQUENCES 
   WHERE SEQUENCE_NAME = UPPER('TP3_NEWSFEED_SEQ')
   
   select TP3_NEWSFEED_SEQ.currval from dual
   
   select * from TP3_NEWSFEED_SEQ
   
select TP3_NEWSFEED_SEQ.currval from dual;
select TP3_NEWSFEED_SEQ.CURRVAL from dual;

SELECT MAX(N_SEQ) FROM TP3_NEWSFEED


   SELECT * FROM TP3_NEWSFEED
   WHERE N_SEQ BETWEEN 121 AND 123
   
   
SELECT *
FROM (SELECT * FROM TP3_NEWSFEED ORDER BY N_SEQ DESC)
WHERE ROWNUM<11

   SELECT * FROM TP3_NEWSFEED
   WHERE N_SEQ BETWEEN 246 -6 AND 246 -1
   ORDER BY N_SEQ DESC
   
   
      SELECT *
   FROM (SELECT * FROM TP3_NEWSFEED ORDER BY N_SEQ DESC)
   WHERE ROWNUM<5 AND N_STEP=0
   
   
      SELECT * FROM TP3_NEWSFEED
   WHERE (N_SEQ BETWEEN 123-6 ROWNUM <= 5) AND N_STEP=0
   ORDER BY N_SEQ DESC
   
   
   select ROWNUM, * from TP3_NEWSFEED where ROWNUM between 4 and 6;
   
   
select * from (select ROWNUM n_seq from (select * from TP3_NEWSFEED order by n_seq asc))
where n_seq between 5 and 10;



   SELECT *
   FROM (SELECT * FROM TP3_NEWSFEED ORDER BY N_SEQ DESC)
   WHERE ROWNUM<6 AND N_STEP=0
   
   
	SELECT * FROM (  SELECT * FROM (SELECT * FROM TP3_NEWSFEED ORDER BY N_SEQ DESC)
   WHERE ROWNUM<6 AND N_SEQ<246)
   
      SELECT *
   FROM (SELECT * FROM TP3_NEWSFEED ORDER BY N_SEQ DESC)
   WHERE ROWNUM<5 AND N_STEP=0
